Add rudimentary VPATH support, but exit with an error if trying to build docs outside source dir.

diff --git a/doc/Makefile.in b/doc/Makefile.in
--- a/doc/Makefile.in
+++ b/doc/Makefile.in
@@ -9,13 +9,21 @@
 # documentation.  Of course, you can just go online at pick up the
 # documentation from http://srtp.sourceforge.net.
 
+srcdir = @srcdir@
+top_srcdir = @top_srcdir@
+top_builddir = @top_builddir@
+VPATH = @srcdir@
+
 # Determine the version of the library
 
-version = $(shell cat ../VERSION)
+version = $(shell cat $(top_srcdir)/VERSION)
 
 
 .PHONY: libsrtpdoc cryptodoc clean
 libsrtpdoc: 
+	@if test ! -e Doxyfile; then \
+		echo "*** Sorry, can't build doc outside source dir"; exit 1; \
+	fi
 	sed 's/LIBSRTPVERSION/$(version)/' header.template > header.tex
 	doxygen
 	sed 's/\subsection/\section/' latex/index.tex > latex/index.tmp
